install.packages("BiocManager")
library (BiocManager)
install("biomaRTt")
install.packages("shiny")
BiocManager::install("biomaRt")
library(biomaRt)
library (shiny)
install.packages("ggplot2")
install.packages ("devtools")
BiocManager::install("rhdf5")
library (devtools)
devtools::install_github("pachterlab/sleuth")
library(sleuth)
install.packages ("cowplot")
install.packages("usethis")
install.packages("igraph")
library (ggplot2)
library (igraph)