install.packages("BiocManager")
library (BiocManager)
install("biomaRTt")
install.packages("shiny")
BiocManager::install("biomaRt")
library(biomaRt)
library (shiny)

install.packages ("devtools")
BiocManager::install("rhdf5")
library (devtools)
devtools::install_github("pachterlab/sleuth")
library(sleuth)
install.packages ("cowplot")
install.packages("usethis")

BiocManager::install("dada2")
library(dada2)
BiocManager::install("phyloseq")
BiocManager::install("microbiome")
library(phyloseq)
